### ISSUE TITLE
exp: using `Ignite`

### ISSUE THREAD

**Issue by shinGangan** [shinGangan/exp-swift-ui-ignite#1]
## Context

Swift UI + Igniteを触ってみる。

- https://github.com/twostraws/Ignite

## Survey

調査内容はここでまとめてる。

https://zenn.dev/gangannikki/scraps/41470872c1ab47

## Roadmap

- [ ] exp: Swift UIのハロワ
- [ ] exp: Igniteのハロワ
- [ ] exp: Igniteで簡単なページを実装する
- [ ] exp: Igniteでexportする
- [ ] exp: exportしたサイトをGitHub Pagesで運用できるようにする
- [ ] exp: jqでjsonの内容チェッカーを実装。GAで動かす
